### ISSUE TITLE
PR review comes up empty

### ISSUE THREAD

**Issue by jordansread** [USGS-R/ds-pipelines-1-course#16]
I am able to trigger a PR (need to branch though this there is no canonical repo), but the review message is empty:

![image](https://user-images.githubusercontent.com/2349007/81189564-56036080-8f7c-11ea-92f3-42bf69e9cad6.png)

**Comment by aappling-usgs** [comment]
I assume this issue is resolved/bypassed, right, @jread-usgs ?

**Comment by jordansread** [comment]
bypassed
