### ISSUE TITLE
unclear how we add reviewers to the copied repo

### ISSUE THREAD

**Issue by jordansread** [USGS-R/ds-pipelines-1-course#20]
![image](https://user-images.githubusercontent.com/2349007/81200410-8a314e00-8f89-11ea-923b-0644ba947c6f.png)

Probably some kind of action to add us both as watchers, then they could assign as reviewers?

**Comment by aappling-usgs** [comment]
I think we may need to add us with read/write permissions. This might be a useful exercise for the new staff to do manually (with some written guidance), though we can also look for options within the Learning Lab framework.

**Comment by jordansread** [comment]
I like that idea.

**Comment by jordansread** [comment]
fixed in a previous PR. I added the "Manage access" stuff
