### ISSUE TITLE
my_happy_script

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/ds-pipelines-1-course#49]
> It's not clear that the code above is the code in my_work_R/my_happy_script.R and that that is the "example script" in the instructions. Also, the code in my_happy_script.R is not the same as in the comment above.

https://github.com/jsadler2/ds-pipelines-1/issues/3#issuecomment-626797525

**Comment by aappling-usgs** [comment]
The plan: Remove the code from the issue comment. Instead, just give a link to that script and then tell them about it.

**Comment by jordansread** [comment]
Also fixed in recent PR #56
