### ISSUE TITLE
suggest patience and reloads

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/ds-pipelines-1-course#52]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/12039957/81594645-3fe80c80-938f-11ea-9171-b6ac64945372.png">

**Comment by aappling-usgs** [comment]
Jordan and Jeff also ran into this

Jeff:
> when I assigned myself issue #1, nothing happened. It looks like JR ran into this too. I added a comment to the existing issue https://github.com/USGS-R/ds-pipelines-1-course/issues/12

**Comment by jordansread** [comment]
Yeah, the refreshing seems to be needed on a lot of the comments in my experience. We'll have to remind early and often.

**Comment by aappling-usgs** [comment]
I added a note to 00-overview.md and added reminders to a few ends of files.

**Comment by jordansread** [comment]
fixed in #52

**Comment by jordansread** [comment]
Whoops, was fixed in https://github.com/aappling-usgs/ds-pipelines-1-course/commit/75ec2c903c3228246454bc2b018f66d5c93f50c5
